language: fortran

notifications:
   email:
      recipients:
         - nickpapior@gmail.com
      on_failure: always
      on_success: change

before_install:
   - ln -s .arch.make arch.make
   - sudo apt-get install -qq gfortran

install:
   - make

script:
   - make check
