language: c

notifications:
   email:
      recipients:
         - nickpapior@gmail.com
      on_failure: always
      on_success: change

before_install:
   - mkdir obj
   - cd obj
   - echo "TOP_DIR=.." > Makefile
   - echo "include ../Makefile" >> Makefile
   - sudo apt-get install -qq gfortran

install:
   - make

script:
   - echo SKIPPING CHECK FOR NOW
